In [1]:
import numpy as np

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

In [2]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
type(l)

list

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

In [7]:
a

array([1., 2., 3., 4., 5.])

In [8]:
a.ndim

1

In [9]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
c.ndim

2

In [11]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [12]:
d.ndim

4

In [13]:
a

array([1., 2., 3., 4., 5.])

In [14]:
a[2]

np.float64(3.0)

In [15]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c[0][2]

np.int64(3)

In [18]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [19]:
d[0][0][1][1]

np.int64(5)

In [20]:
a

array([1., 2., 3., 4., 5.])

In [21]:
a.shape

(5,)

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
c.shape

(3, 3)

In [24]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [25]:
d.shape

(1, 1, 3, 3)

In [26]:
a.dtype

dtype('float64')

In [27]:
c.dtype

dtype('int64')

## Accessing/Changing specific elements, rows & columns etc.

In [28]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a[0][1] = 200

In [30]:
a

array([[  1, 200,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

# Zeros/Ones method in NumPy

In [31]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
zero.dtype

dtype('float64')

In [33]:
one = np.ones((3,4), dtype=int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.full((3,4), 60, dtype=float)

array([[60., 60., 60., 60.],
       [60., 60., 60., 60.],
       [60., 60., 60., 60.]])

In [35]:
np.random.rand(3,4)

array([[0.95446929, 0.85308899, 0.49475974, 0.73327707],
       [0.01182462, 0.39107821, 0.86500015, 0.19141589],
       [0.1523515 , 0.65440602, 0.93240366, 0.96278293]])

In [36]:
np.random.randint(10, 100, size=(3,4))

array([[48, 21, 74, 21],
       [54, 62, 63, 94],
       [64, 10, 60, 97]], dtype=int32)

In [37]:
# Lists vs Arrays
heights_list = [1.75, 1.68, 1.80]
weight_list = [65, 50, 75]

# This works with NumPy:
heights_arr = np.array(heights_list)
weights_arr = np.array(weight_list)

bmi = weights_arr / (heights_arr ** 2)
print(bmi)

[21.2244898  17.7154195  23.14814815]
